const express = require("express");
const router = express.Router();

/* Feature routes */
const userRoutes = require("./userRoute");
const staffRoutes = require("./staffRoute");
const billstackRoutes = require("./billstackRoutes");
const txnRoutes = require("./transactionRoute");
const notifyRoutes = require("./notificationRouter");
const easyRoutes = require("./easyAccessRoute");
const permRoutes = require("./permissionRoute");
const roleRoutes = require("./roleRoute");
const logRoutes = require("./activityLogRoute");
const planRoutes = require("./servicePlanRoute");
const apiProviderRoutes = require("./apiProviderRoute");
const paymentProviderRoutes = require("./paymentProviderRoute");
const walletRoutes = require("./walletRoute");
const serviceRoutes = require("./servicesRoute");
const subServiceRoutes = require("./subServicesRoute");
const categoryProviderRoutes = require("./categoryProviderRoute");
const statisticsRoutes = require("./statisticRoute");
const configRoutes = require("./configRoute");
const { getPublicBranding } = require("../controllers/configController");
const tenantRoutes = require("./tenantRoute");
const { getPublicTenantBranding, getPublicTenantPlans } = require("../controllers/tenantController");

/* Mount each base route */
router.get("/public/branding", getPublicBranding);
router.get("/public/tenant/:slug/branding", getPublicTenantBranding);
router.get("/public/tenant/:slug/plans", getPublicTenantPlans);
router.use("/auth", userRoutes);
router.use("/staff", staffRoutes);
router.use("/billstack", billstackRoutes);
router.use("/transactions", txnRoutes);
router.use("/notifications", notifyRoutes);
router.use("/easyaccess", easyRoutes);
router.use("/permissions", permRoutes);
router.use("/roles", roleRoutes);
router.use("/logs", logRoutes);
router.use("/plans", planRoutes);
router.use("/network-providers", apiProviderRoutes);
router.use("/payment-providers", paymentProviderRoutes);
router.use("/wallets", walletRoutes);
router.use("/services", serviceRoutes);
router.use("/subservices", subServiceRoutes);
router.use("/category-providers", categoryProviderRoutes);
router.use("/statistics", statisticsRoutes);
router.use("/config", configRoutes);
router.use("/tenants", tenantRoutes);
module.exports = router;
